# Generated by Django 4.2 on 2023-11-02 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6c8bd102-280f-4df2-8f0f-58ba423ac32d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
