# Generated by Django 4.2 on 2023-11-02 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_todo_user_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('785be47f-c6c0-4713-a2c0-e1a9ee87b03c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('785be47f-c6c0-4713-a2c0-e1a9ee87b03c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
